
name: host-libgraph

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        working-directory: host/libgraph
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        working-directory: host/libgraph
        run: cmake --build build -j
      - name: Test
        working-directory: host/libgraph
        run: ctest --test-dir build --output-on-failure
