name: host-suite-qa
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        working-directory: tools
        run: npm install
      - name: Build
        working-directory: tools
        run: npm run build
      - name: Run QA
        working-directory: tools
        run: npm run qa
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: host-suite-artifacts
          path: tools/artifacts